name: child-workflow.yml

on:
  workflow_call:
    inputs:
      changes:
        description: "The changes"
        required: true
        type: string
      run:
        description: "Do I run"
        required: true
        type: boolean
        default: false
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "changed files"
        if: ${{ inputs.run }}
        run: echo "${{ inputs.changes }}"

      - name: "child one"
        if: ${{ contains(inputs.changes, 'src/children/one') }}
        run: echo "i modified child one"

      - name: "child two" 
        if: ${{ contains(inputs.changes, 'src/children/two') }}
        run: echo "i modified child two"
      
      - name: "children"
        if: ${{ contains(inputs.changes, 'src/children/children.yml') }}
        run: echo "i modified my children"

      - name: "only child"
        if: ${{ contains(inputs.changes, 'src/onlychild') }}
        run: echo "i modified my only child"