name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        default: "30"
        description: "Number of days to keep"
        required: false
        type: string
      runs:
        default: "10"
        description: "Number of runs to keep"
        required: false
        type: string



jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: ${{ inputs.runs }} 
