name: main

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - "main"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      srcout: ${{ steps.filter.outputs.src }}
      changes: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - src/**

  basic:
    needs: changes
    if: ${{ needs.changes.outputs.srcout == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "echo changes"
        run: echo "${{ needs.changes.outputs.changes }}"
  
  child:
    uses: ./.github/workflows/child1.yml
