name: main

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - "main"
    
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      srcout: ${{ steps.filterid.outputs.src }}
      filters: ${{ steps.filterid.outputs.changes }}
      files: ${{ steps.filterid.outputs.src_files }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filterid
      with:
        list-files: 'json'
        filters: |
          src:
            - src/**

  basic:
    environment: dev
    concurrency:
      cancel-in-progress: false
      group: dev-env
    needs: changes
    if: ${{ needs.changes.outputs.srcout == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "changed filters"
        run: echo "${{ needs.changes.outputs.filters }}"

      - name: "changed files"
        run: echo "${{ needs.changes.outputs.files }}"

      - name: "child one"
        if: ${{ contains(needs.changes.outputs.files, 'src/children/one') }}
        run: echo "i modified child one"

      - name: "child two" 
        if: ${{ contains(needs.changes.outputs.files, 'src/children/two') }}
        run: echo "i modified child two"
      
      - name: "children"
        if: ${{ contains(needs.changes.outputs.files, 'src/children/children.yml') }}
        run: echo "i modified my children"

      - name: "only child"
        if: ${{ contains(needs.changes.outputs.files, 'src/onlychild') }}
        run: echo "i modified my only child"
  
  child:
    uses: ./.github/workflows/child-workflow.yml
    if: ${{ needs.changes.outputs.srcout == 'true' && github.event_name != 'pull_request' }}
    needs: changes
    with:
      changes: ${{ needs.changes.outputs.files }}
  
  action-one:
    if: ${{ needs.changes.outputs.srcout == 'true' && github.event_name != 'pull_request' }}
    environment: prod
    concurrency:
      cancel-in-progress: false
      group: prod-env
    needs: changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # local actions need a checkout
    - name: "action-one"
      uses: ./.github/actions/action-one
      with:
        changes: ${{ needs.changes.outputs.files }}
        run: ${{ needs.changes.outputs.srcout == 'true' }}
