name: main

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - "main"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      srcout: ${{ steps.filterid.outputs.src }}
      filters: ${{ steps.filterid.outputs.changes }}
      files: ${{ steps.filterid.outputs.src_files }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filterid
      with:
        list-files: 'json'
        filters: |
          src:
            - src/**
    - name: "output changes to env"
      run: echo "are_files_changed=${{ steps.filterid.outputs.src }}" >> $GITHUB_ENV
    - name: "output files to env"
      run: echo "files_changed"=${{ steps.filterid.outputs.src_files }}" >> $GITHUB_ENV

  basic:
    needs: changes
    if: ${{ needs.changes.outputs.srcout == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "changed filters"
        run: echo "${{ needs.changes.outputs.filters }}"

      - name: "changed files"
        run: echo "${{ needs.changes.outputs.files }}"

      - name: "child one"
        if: ${{ contains(needs.changes.outputs.files, 'src/children/one') }}
        run: echo "i modified child one"

      - name: "child two" 
        if: ${{ contains(needs.changes.outputs.files, 'src/children/two') }}
        run: echo "i modified child two"
      
      - name: "children"
        if: ${{ contains(needs.changes.outputs.files, 'src/children/children.yml') }}
        run: echo "i modified my children"

      - name: "only child"
        if: ${{ contains(needs.changes.outputs.files, 'src/onlychild') }}
        run: echo "i modified my only child"
  
  child:
    uses: ./.github/workflows/child-workflow.yml
    if: ${{ env.are_files_changed == 'true' }}
    needs: changes
    with:
      changes: ${{ needs.changes.outputs.files }}
  
  action-one:
    needs: changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "action-one"
      uses: ./.github/actions/action-one
      with:
        changes: ${{ env.files_changed }}

