name: notify

on:
  pull_request:
    types:
      - closed
  workflow_run:
    workflows:
      - "main"
    types:
      - completed
    branches:
      - "*"
      - "main"
  push:
    branches:
      - "main"
  deployment:
  deployment_status:

    
jobs:
  on-all:
    runs-on: ubuntu-latest
    steps:
      - name: "${{ github.event_name }}"
        run: echo '${{ toJSON(github) }}'

  # on-pr:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.pull_request.head.repo.fork }} || github.event.ref == 'refs/heads/main' || github.event.pull_request.merged == true
  #   steps:
  #     - name: "output event"
  #       run: echo ${{ github.event }}

          
  # on-deploy:
  #   runs-on: ubuntu-latest
  #   # Trigger on CICD Pipeline for trunk runs
  #   if: github.event.workflow.name == 'main' && github.event.ref == 'refs/heads/main'
  #   steps:
  #     - name: "output event"
  #       run: echo ${{ github.event }}