name: notify on workflow run

on:
  workflow_run:
    workflows:
      - "main-pipeline"
    types:
      - completed
    branches:
      - "*"
      - "main"
  deployment_status:

    
jobs:
  on-workflow:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["failure","success"]'), github.event.workflow_run.conclusion)
    steps:
      - name: "${{ github.event_name }}"
        run: echo '${{ toJSON(github) }}'
      - name: env vars
        run: set
      - name: summary
        run: | 
          echo "# Trigger Summary" >> $GITHUB_STEP_SUMMARY
          echo "Event Name: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Event Type: ${{ github.event.workflow_run.event }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Name: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Type: ${{ github.ref_type }}" >> $GITHUB_STEP_SUMMARY
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}" >> $GITHUB_STEP_SUMMARY
    
  on-deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow.name == 'main-pipeline' && contains(fromJSON('["failure","success"]'), github.event.deployment_status.state)
    steps:
      - name: "${{ github.event_name }}"
        run: echo '${{ toJSON(github) }}'
      - name: env vars
        run: set
      - name: "output event"
        run: |
          echo "Deployed to: ${{ github.event.deployment_status.environment }}"
          echo "Deployed outcome: ${{ github.event.deployment_status.state }}"
      - name: summary
        run: |
          echo "# Trigger Summary" >> $GITHUB_STEP_SUMMARY
          echo "Event Name: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Event Type: ${{ github.event.workflow_run.event }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Name: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Type: ${{ github.ref_type }}" >> $GITHUB_STEP_SUMMARY
          echo "Deployed to: ${{ github.event.deployment_status.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Deployed State: ${{ github.event.deployment_status.state }}" >> $GITHUB_STEP_SUMMARY
