name: notify on pr merge

on:
  pull_request:
    types:
      - closed

jobs:
  on-pr-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true' && github.event.base_ref == 'main'
    steps:
      - name: "${{ github.event_name }}"
        run: echo '${{ toJSON(github) }}'
      - name: env vars
        run: set
      - name: "output event"
        run: | 
          echo "# Trigger Summary" >> $GITHUB_STEP_SUMMARY
          echo "Event Name: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Event Type: ${{ github.event.workflow_run.event }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Name: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Type: ${{ github.ref_type }}" >> $GITHUB_STEP_SUMMARY